server:
  port: 8080
  servlet:
    context-path: /identity


spring:
  datasource:
    url: 'jdbc:mysql://localhost:3308/ca_house_identity'
    username: root
    password: Myca@1236
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
