server:
  port: 8080
  servlet:
    context-path: /identity


spring:
  datasource:
    url: 'jdbc:mysql://localhost:3308/ca_house_identity'
    username: root
    password: Myca@1236
  jpa:
    hibernate:
      ddl-auto: update


jwt:
  signer-key: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600
  refreshable-duration: 360000