server:
  port: 8888

app:
  api-prefix: /api
  user-endpoint: http://user-service:8080
  motel-endpoint: http://motel-service:8082
  post-endpoint: http://post-service:8084
  noti-endpoint: http://noti-service:8083

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: ${app.user-endpoint}
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=1

        - id: motel-service
          uri: ${app.motel-endpoint}
          predicates:
            - Path=${app.api-prefix}/motel/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: ${app.noti-endpoint}
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=1

        - id: post-service
          uri: ${app.post-endpoint}
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=1