server:
  port: 8888

app:
  api-prefix: /api


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=1

        - id: motel-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/motel/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=1