server:
  port: 8080
  servlet:
    context-path: /identity


spring:
  datasource:
    url: 'jdbc:mysql://localhost:3308/ca_house_identity'
    username: root
    password: Myca@1236
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  signer-key: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600
  refreshable-duration: 360000

app:
  outbound:
    client_id: "220674217445-aktqm98i9kda2gnvnjvlfgqbe1o79s07.apps.googleusercontent.com"
    client_secret: "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"
    redirect_uri: "http://localhost:5173"