server:
  port: 8080
  servlet:
    context-path: /identity

app:
#  user-endpoint: http://localhost:8080
#  file-endpoint: http://localhost:8081
#  motel-endpoint: http://localhost:8082
#  post-endpoint: http://localhost:8084
#  noti-endpoint: http://localhost:8083
#  kafka: localhost:9094
#  db-string: jdbc:mysql://localhost:3308/ca_house_identity
#  redirect_url: http://localhost:3000
  kafka: kafka:9092
  user-endpoint: http://user-service:8080
  file-endpoint: http://file-service:8081
  motel-endpoint: http://motel-service:8082
  post-endpoint: http://post-service:8084
  noti-endpoint: http://noti-service:8083
  db-string: jdbc:mysql://mysql_user:3306/ca_house_identity
  redirect_url: https://ca-house-nextjs.vercel.app/

  outbound:
    client_id: "220674217445-aktqm98i9kda2gnvnjvlfgqbe1o79s07.apps.googleusercontent.com"
    client_secret: "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"
    redirect_uri: ${app.redirect_url}

spring:
  datasource:
    url: ${app.db-string}
    username: root
    password: Myca@1236
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${app.kafka}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  signer-key: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600
  refreshable-duration: 360000