server:
  port: 8082
  servlet:
    context-path: /motel

spring:
  application:
    name: motel-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Ho_Chi_Minh
  datasource:
    url: 'jdbc:postgresql://localhost:5432/ca_house_motel'
    username: root
    password: Poca@1236
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



