server:
  port: 8082
  servlet:
    context-path: /motel

spring:
  application:
    name: motel-service
  datasource:
    url: 'jdbc:postgresql://localhost:5432/ca_house_motel'
    username: root
    password: Poca@1236
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB



